name: Build and Deploy

on:
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 12
              run: yarn install
              run: yarn build
              run: yarn test
            - name: Push build to S3
              uses: sai-sharan/aws-s3-sync-action@master
              with:
                access_key: ${{ secrets.ACCESS_KEY }}
                secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
                region: 'us-east-1'
                source: 'build'
                destination_bucket: ${{ secrets.AWS_S3_BUCKET }}
                #destination_prefix: ${{ secrets.DESTINATION_PREFIX }}
                exclude: '.git/*'
                delete: true
                quiet: false
